version: '3'

services:
  predictor:
    image: malwarerevealer/predictor
    build: ./prediction-server
    ports:
      - 8080:80
    restart: on-failure
    networks:
      - backend

  extractor:
    image: malwarerevealer/extractor-server
    build: ./extractor/server
    restart: on-failure
    networks:
      - backend

networks:
  backend:
